import { Metadata } from "next";
import { Sidebar } from "../../components/Sidebar";

export const metadata: Metadata = {
  title: {
    default: "Inventory",
    template: "%s",
  },
  description: "Generated by create next app",
};
export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen w-screen bg-blackBGLoginPage">
      <div className="flex">
        <Sidebar />
        {children}
      </div>
    </main>
  );
}
